# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowmgmt', '0001_initial'),
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[(b'GEN', b'\xe9\x80\x9a\xe7\x94\xa8Web\xe5\xba\x94\xe7\x94\xa8\xe6\x88\x96C/S\xe6\x9e\xb6\xe6\x9e\x84\xe4\xba\xa7\xe5\x93\x81\xef\xbc\x8c\xe5\xbc\xba\xe5\x8c\x96\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe4\xbe\xa7\xe5\xae\x89\xe5\x85\xa8'), (b'CLIENT', b'PC\xe6\x88\x96\xe7\xa7\xbb\xe5\x8a\xa8\xe5\xae\xa2\xe6\x88\xb7\xe7\xab\xaf\xe5\xba\x94\xe7\x94\xa8\xef\xbc\x8c\xe5\xbc\xba\xe5\x8c\x96\xe7\xbb\x88\xe7\xab\xaf\xe5\xae\x89\xe5\x85\xa8'), (b'OTHER', b'\xe5\x85\xb6\xe5\xae\x83')], default=b'GEN', max_length=32)),
                ('no', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('objective', models.CharField(blank=True, max_length=1024, null=True)),
                ('introduction', models.CharField(blank=True, max_length=4096, null=True)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('mandays', models.FloatField(default=0.0)),
                ('manday_cost', models.FloatField(default=1000.0)),
                ('currency_unit', models.CharField(default=b'\xe5\x85\x83', max_length=32)),
                ('hardware_cost', models.FloatField(default=0.0)),
                ('software_cost', models.FloatField(default=0.0)),
                ('other_cost', models.FloatField(default=0.0)),
                ('annual_license_cost', models.FloatField(default=0.0)),
                ('other_annual_cost', models.FloatField(default=0.0)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architect_projects', to='usermgmt.User')),
                ('business_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_rep_projects', to='usermgmt.User')),
                ('chief_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_projects', to='usermgmt.User')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_projects', to='usermgmt.User')),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_handler_projects', to='usermgmt.User')),
                ('dev_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_rep_projects', to='usermgmt.User')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_projects', to='flowmgmt.ProjectFlow')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_projects', to='usermgmt.User')),
                ('members', models.ManyToManyField(blank=True, related_name='member_projects', to='usermgmt.User')),
                ('op_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_projects', to='usermgmt.User')),
                ('peer_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewer_projects', to='usermgmt.User')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmgmt.ProjectPhase')),
                ('purchasing_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_rep_projects', to='usermgmt.User')),
                ('qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_projects', to='usermgmt.User')),
                ('qc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_projects', to='usermgmt.User')),
                ('security_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_reviewer_projects', to='usermgmt.User')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_projects', to='usermgmt.User')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='stakeholder_projects', to='usermgmt.User')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmgmt.ProjectStatus')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='usermgmt.Team')),
                ('test_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_rep_projects', to='usermgmt.User')),
                ('user_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rep_projects', to='usermgmt.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_handler_approvals', to='usermgmt.User')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmgmt.ProjectOption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approvals', to='projectmgmt.Project')),
                ('trustee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_trustee_approvals', to='usermgmt.User')),
            ],
        ),
    ]
