# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('extra_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('remind_method', models.CharField(choices=[(b'DEADLINE', b'\xe5\x88\xb0\xe6\x9c\x9f\xe6\x8f\x90\xe9\x86\x92'), (b'PERD', b'\xe5\x91\xa8\xe6\x9c\x9f\xe6\x80\xa7\xe6\x8f\x90\xe9\x86\x92'), (b'ONETIME', b'\xe4\xbb\x85\xe6\x8f\x90\xe9\x86\x92\xe4\xb8\x80\xe6\xac\xa1')], default=b'DEADLINE', max_length=16)),
                ('is_finished', models.BooleanField(default=False)),
                ('finish_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemindLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('seconds_delta', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineRemind',
            fields=[
                ('remind_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='remindmgmt.Remind')),
                ('deadline_time', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('remindmgmt.remind',),
        ),
        migrations.CreateModel(
            name='OneTimeRemind',
            fields=[
                ('remind_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='remindmgmt.Remind')),
                ('remind_time', models.DateTimeField()),
            ],
            bases=('remindmgmt.remind',),
        ),
        migrations.CreateModel(
            name='PeriodRemind',
            fields=[
                ('remind_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='remindmgmt.Remind')),
                ('first_remind_time', models.DateTimeField()),
                ('repeat_method', models.CharField(choices=[(b'FIX', b'\xe5\x9b\xba\xe5\xae\x9a\xe9\x97\xb4\xe9\x9a\x94'), (b'MONTHLY', b'\xe6\x8c\x89\xe6\x9c\x88\xe6\x8f\x90\xe9\x86\x92'), (b'YEARLY', b'\xe6\x8c\x89\xe5\xb9\xb4\xe6\x8f\x90\xe9\x86\x92')], default=b'FIX', max_length=16)),
                ('interval_seconds', models.BigIntegerField()),
                ('expire_time', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
            ],
            bases=('remindmgmt.remind',),
        ),
        migrations.AddField(
            model_name='remindlog',
            name='remind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remind_logs', to='remindmgmt.Remind'),
        ),
        migrations.AddField(
            model_name='remind',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user_reminds', to='usermgmt.User'),
        ),
        migrations.AddField(
            model_name='remind',
            name='receivers',
            field=models.ManyToManyField(related_name='receiver_reminds', to='usermgmt.User'),
        ),
    ]
