# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[(b'APP', b'\xe4\xba\xa7\xe5\x93\x81/\xe5\xba\x94\xe7\x94\xa8/\xe6\x9c\x8d\xe5\x8a\xa1'), (b'CLUSTER', b'\xe9\x9b\x86\xe7\xbe\xa4/\xe8\x99\x9a\xe6\x8b\x9f\xe8\x8a\x82\xe7\x82\xb9'), (b'DB', b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93'), (b'MIDDLEWARE', b'\xe4\xb8\xad\xe9\x97\xb4\xe4\xbb\xb6'), (b'SERVICE', b'\xe7\xb3\xbb\xe7\xbb\x9f\xe6\x9c\x8d\xe5\x8a\xa1'), (b'OS', b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f'), (b'SERVER', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'STORAGE', b'\xe5\xad\x98\xe5\x82\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'NETDEV', b'\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe5\xa4\x87'), (b'ROOM', b'\xe6\x9c\xba\xe6\x88\xbf'), (b'OTHER', b'\xe5\x85\xb6\xe5\xae\x83')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'ONLINE', b'\xe6\xad\xa3\xe5\xb8\xb8/\xe6\x9c\x89\xe6\x95\x88'), (b'OFFLINE', b'\xe5\x86\xb7\xe5\xa4\x87/\xe6\x9c\xaa\xe5\x90\xaf\xe7\x94\xa8'), (b'READY', b'\xe5\xb0\xb1\xe7\xbb\xaa/\xe5\x87\x86\xe5\xa4\x87\xe4\xb8\x8a\xe7\xba\xbf'), (b'EXPIRE', b'\xe5\xb7\xb2\xe5\x81\x9c\xe6\xad\xa2\xe7\xbb\xb4\xe6\x8a\xa4/\xe5\x87\x86\xe5\xa4\x87\xe4\xb8\x8b\xe7\xba\xbf'), (b'INVALID', b'\xe5\xb7\xb2\xe4\xbd\x9c\xe5\xba\x9f')], default=b'ONLINE', max_length=32)),
                ('ports', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_domains', to='usermgmt.Company')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(blank=True, max_length=64, null=True)),
                ('destination_label', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.GenericIPAddressField()),
                ('category', models.CharField(choices=[(b'INNER', b'\xe5\x86\x85\xe7\xbd\x91\xe4\xb8\x9a\xe5\x8a\xa1IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'OUTER', b'\xe5\xa4\x96\xe7\xbd\x91\xe4\xb8\x9a\xe5\x8a\xa1IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'DMZ', b'DMZ\xe4\xb8\x9a\xe5\x8a\xa1IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'ADM', b'\xe7\xae\xa1\xe7\x90\x86\xe7\xbd\x91IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'BAK', b'\xe5\xa4\x87\xe4\xbb\xbd\xe7\xbd\x91IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'VPN', b'\xe4\xb8\x93\xe7\xbd\x91IP\xe5\x9c\xb0\xe5\x9d\x80'), (b'OTHER', b'\xe5\x85\xb6\xe5\xae\x83IP\xe5\x9c\xb0\xe5\x9d\x80')], default=b'OUTER', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ips', to='usermgmt.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleWareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('user_portal', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_portal', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.AppType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='DB',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.DatabaseType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='MIDDLEWARE',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('middleware_name', models.CharField(max_length=64)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.MiddleWareType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='NETDEV',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_portal', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.NetworkDeviceType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('os_name', models.CharField(max_length=64)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.OsType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='ROOM',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('city', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=128, null=True)),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='SERVER',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_portal', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itsm.ServerType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='SERVICE',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('service_name', models.CharField(max_length=128)),
            ],
            bases=('itsm.ci',),
        ),
        migrations.CreateModel(
            name='STORAGE',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.CI')),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_portal', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.StorageType')),
            ],
            bases=('itsm.ci',),
        ),
        migrations.AddField(
            model_name='integrationrelation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_relations', to='itsm.CI'),
        ),
        migrations.AddField(
            model_name='integrationrelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='itsm.CI'),
        ),
        migrations.AddField(
            model_name='domain',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_domains', to='itsm.IP'),
        ),
        migrations.AddField(
            model_name='ci',
            name='admins',
            field=models.ManyToManyField(blank=True, to='usermgmt.User'),
        ),
        migrations.AddField(
            model_name='ci',
            name='bind_domains',
            field=models.ManyToManyField(blank=True, related_name='domain_cis', to='itsm.Domain'),
        ),
        migrations.AddField(
            model_name='ci',
            name='bind_ips',
            field=models.ManyToManyField(blank=True, related_name='ip_cis', to='itsm.IP'),
        ),
        migrations.AddField(
            model_name='ci',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cis', to='usermgmt.Company'),
        ),
        migrations.AddField(
            model_name='ci',
            name='down_stream_cis',
            field=models.ManyToManyField(blank=True, related_name='up_stream_cis', to='itsm.CI'),
        ),
        migrations.AddField(
            model_name='ci',
            name='integrations',
            field=models.ManyToManyField(through='itsm.IntegrationRelation', to='itsm.CI'),
        ),
    ]
