# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=256)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.User')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=b'upload/images')),
                ('content', models.CharField(max_length=4096)),
                ('author', models.CharField(default=b'Jane', max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('pseudo_name', models.CharField(max_length=64, unique=True)),
                ('keywords', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('show_in_front', models.BooleanField(default=True)),
                ('show_in_carousel', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='pagemgmt.Page'),
        ),
    ]
