# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, max_length=1024, null=True)),
                ('image_link', models.CharField(blank=True, max_length=512, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('last_reply_time', models.DateTimeField(auto_now=True)),
                ('praised_by', models.ManyToManyField(blank=True, related_name='praised_msgs', to='usermgmt.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_circle_msgs', to='usermgmt.User')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_circle_msgs', to='msgmgmt.CircleMessage')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, max_length=1024, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('sender_delete', models.BooleanField(default=False)),
                ('receiver_delete', models.BooleanField(default=False)),
                ('last_reply_time', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_msgs', to='usermgmt.User')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_msgs', to='usermgmt.User')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_msgs', to='msgmgmt.Message')),
            ],
        ),
    ]
